### PR TITLE
feat: add the entity module's stubs

### PR DESCRIPTION
**Pull request by Acedyn**
- Make the socketio dependency more relax to allow backward compatibility
- Add stubs for the entity module
- Inherit from the entity module for the Shot, Sequence and Episode classes (Assets should inherit too but out of scope for now)
- Change the typing of the "status" field to follow the way it is defined in the [Zou API](https://github.com/cgwire/zou/blob/main/zou/app/models/entity.py#L9)

### CODE REVIEW

**Comment by johhnry** [comment]
Thanks a lot! Please do a `poe check` to see if the code is correct.

**Comment by Acedyn** [comment]
I'm getting an error with mypy check because of an inconsistancy between the pyproect wich allows python 3.10, but the project module uses [typing.NotRequired](https://docs.python.org/3/library/typing.html#typing.NotRequired) wich is only available for python 3.11. I'm not sure if the required version should be bumped to 3.11 or the use of typing.NotRequired should be removed given that 3.10 is still largely used on most DCCs today.

**Comment by johhnry** [comment]
@Acedyn You're right, we can use [`typing-extension`'s `NotRequired`](https://typing-extensions.readthedocs.io/en/latest/index.html#typing_extensions.NotRequired) and downgrade the required version to 3.10

**Comment by Acedyn** [comment]
> @Acedyn You're right, we can use [`typing-extension`'s `NotRequired`](https://typing-extensions.readthedocs.io/en/latest/index.html#typing_extensions.NotRequired) and downgrade the required version to 3.10

This is not done in this PR I will do it in a different PR later

**Pull request merged**
